browser: chrome

url:
  homePage: http://146.59.32.4/index.php
  contactUsPage: ?controller=contact
  loginPage: ?controller=authentication&back=my-account
  basketPage: ?controller=cart&action=show
  accessoriesPage: ?id_category=6&controller=category&id_lang=2
  myAccountPage: ?controller=my-account
  createAccountPage: ?controller=authentication&create_account=1
  artPage: ?id_category=9&controller=category&id_lang=2

users:
  user1:
    firstName: Alexander
    lastName: Hamilton
    gender: male
    email: alex@hamilton.com
    password: password
    birthdate: 05/01/1970

addresses:
  address1:
    street: ExampleStreet 19
    city: Phoenix
    postalCode: 85001
    phoneNumber: 100-200-300
    country: United States
    state: Arizona
    companyName: exampleCompany


testData:
  defaultWait: 10
  productName1: HUMMINGBIRD
  productName2: THE BEST IS YET POSTER
  quantity2: 3
  quantity3: 2
  numberOfProducts3: 2
  categoryName4: Art
  posterName4: THE BEST IS YET POSTER
  paymentStatus4: Awaiting check payment
  lowerPriceFilter5: 13
  higherPriceFilter5: 15
  numberOfRepetitions6: 10

