browser: chrome

url:
  homePage: http://146.59.32.4/index.php
  contactUsPage: ?controller=contact
  loginPage: ?controller=authentication&back=my-account
  basketPage: ?controller=cart&action=show
  accessoriesPage: ?id_category=6&controller=category&id_lang=2
  artPage: ?id_category=9&controller=category&id_lang=2

users:
  user1:
    firstName: Alexander
    lastName: Hamilton
    gender: male
    email: alex@hamilton.com
    password: password
    birthdate: 05/01/1970


testData:
  country: United States
  postalCode: 85001
  state: Arizona
  posterName: THE BEST IS YET POSTER





